<?php

namespace GM\ProjetBundle\Repository;

/**
 * DossierMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierMissionRepository extends \Doctrine\ORM\EntityRepository
{
}
