<?php

namespace GM\ProjetBundle\Repository;

/**
 * FraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisRepository extends \Doctrine\ORM\EntityRepository
{
}
